### PR TITLE
Basic collision detection, fix for a camera bug in rendering, some mo…

### PR DESCRIPTION
**Pull request by Axellent**
…re initialization improvements

### CODE REVIEW

**Review by optimusprime94 — CHANGES_REQUESTED** [review]
Looking Good 👍 , but 👎 :

# AspectRatio is not used when creating default Cameracomponent?
# If no Camera is added is cameracomponents 0 or null? maybe a crash can occur if the dictionary is only created when a camera is added.
# naming conventions: in one loop we have modelKeyvaluePair and in another velocityComponentPair. 
# UpdateModel: seems a little bit game specific?

**Comment by Axellent** [comment]
Issues have been addressed and everything has been merged to a recent version of master meaning the final merge should be simple

**Review by simon-f-kevin — APPROVED** [review]
Nick tyckte att det såg bra ut

**Review by xXDragonZlayerXx — APPROVED** [review]
Pretty good, but remember to reuse the code in the entityfactory when creating a player with a camera.

**Pull request merged**
