### PR TITLE
Application level culling + better collision detection preformance

### PR DESCRIPTION
**Pull request by simon-f-kevin**
We only render models which intersets with the cameras boundingFrustum. 
The collision detection was reworked to only compare players to other players and players to blocks. This should decrease number of comparisons by several ~~hundred~~ percent.

### CODE REVIEW

**Review by xXDragonZlayerXx — CHANGES_REQUESTED** [review]
You can't reduce collision checks by several hundred percent, it can't go further than a 100%.

**Comment by xXDragonZlayerXx** [comment]
It would be better if only checking player collisions was optional, right now that is a very game-specific design choice in our engine.

**Review by JBMATANDA — APPROVED** [review]

**Review by xXDragonZlayerXx — APPROVED** [review]

**Review by optimusprime94 — APPROVED** [review]
looks OK

**Review by optimusprime94 — COMMENTED** [review]
En grejj jag fundera på: kollar vi kollisions för varje spelare parallellt? var händer om de kolliderat med varandra, kan det bli dubbla kollisions?

**Pull request merged**
